# <span style="color:red">**SPRINT 12:**</span> <span style="color:YELLOW"> APIs REST </span>

**OBJETIVO**:
Utiliza APIs públicas para:
- Consultar datos  
- Filtrarlos  
- Guardarlos en un DataFrame de pandas

Aplicar lo aprendido sobre:
- APIs REST  
- Métodos HTTP  
- Códigos de estado  

;ás información sobre `requests` en:
-   `https://www.w3schools.com/python/module_requests.asp` 
-   `https://requests.readthedocs.io/en/latest/user/quickstart/#make-a-request`

## Nivel 1: 
Exploración básica con library `requests` con una API de laboratorio. URL: https://jsonplaceholder.typicode.com/

In [133]:
import requests
import pandas as pd

- URL = 'https://www.xxxx.com' -> Para evitar escribir cada vez la url (o aprovechar parcialmente el código), guardar la URL como una variable.  
- Código para solicitar: var_resposta = **requests.metodo(url)** -> Lo guardamos en forma de variable para poder explorar luego
- var_resposta.status_code:
    .status_code
    .json()
    .request
    .text
    .url
    .headers
    .close()
    others (ver `https://www.w3schools.com/python/module_requests.asp`)


Tipus de code_status:
- 1xx information
- 2xx success: request received, understood and accepted
- 3xx redirection
- 4xx client error
- 5xx server error

In [134]:
url_nivel_1 = 'https://jsonplaceholder.typicode.com/'

In [135]:
resposta_1 = requests.get(url_nivel_1)
resposta_1

### 1.1 Consultas GET básicas

Consulta l’API pública JSONPlaceholder usando el método GET para obtener:

- Llista de publicacions (/posts)  
- Llista d’usuaris (/users)  
- Llista de tasques (/todos)  

### 1.2 Muestra cantidad de cada recurso y estado de la petición

In [136]:
# Lista de posts
posts_resp = requests.get(url_nivel_1 + 'posts')
print('Posts - Codigo estado:', posts_resp.status_code)
print('Total posts:', len(posts_resp.json()))

# Llista d'usuaris
users_resp = requests.get(url_nivel_1 + 'users')
print('\nUsuaris - Codigo estado:', users_resp.status_code)
print('Total usuaris:', len(users_resp.json()))

# Llista de tasques
todos_resp = requests.get(url_nivel_1 + 'todos')
print('\nTodos - Codigo estado:', todos_resp.status_code)
print('Total todos:', len(todos_resp.json()))

Posts - Codigo estado: 200
Total posts: 100

Usuaris - Codigo estado: 200
Total usuaris: 10

Todos - Codigo estado: 200
Total todos: 200

In [137]:
posts_resp.headers

{'Date': 'Mon, 02 Mar 2026 18:41:56 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'access-control-allow-credentials': 'true', 'Cache-Control': 'max-age=43200', 'Content-Encoding': 'gzip', 'etag': 'W/"6b80-Ybsq/K6GwwqrYkAsFxqDXGC7DoM"', 'expires': '-1', 'nel': '{"report_to":"heroku-nel","response_headers":["Via"],"max_age":3600,"success_fraction":0.01,"failure_fraction":0.1}', 'pragma': 'no-cache', 'report-to': '{"group":"heroku-nel","endpoints":[{"url":"https://nel.heroku.com/reports?s=5v%2ByXjWy7zPec1xEPcVn%2F8BaKQcCSxBnVZwaC9wjEws%3D\\u0026sid=e11707d5-02a7-43ef-b45e-2cf4d2036f7d\\u0026ts=1771458576"}],"max_age":3600}', 'reporting-endpoints': 'heroku-nel="https://nel.heroku.com/reports?s=5v%2ByXjWy7zPec1xEPcVn%2F8BaKQcCSxBnVZwaC9wjEws%3D&sid=e11707d5-02a7-43ef-b45e-2cf4d2036f7d&ts=1771458576"', 'Server': 'cloudflare', 'vary': 'Origin, Accept-Encoding', 'via': '2.0 heroku-router', 'x-content-type-options': 'nosniff', 'x-powered-by': 'Express', 'x-ratelimit-limit': '1000', 'x-ratelimit-remaining': '999', 'x-ratelimit-reset': '1771458591', 'Age': '9999', 'cf-cache-status': 'HIT', 'CF-RAY': '9d6289da7b95026b-MAD', 'alt-svc': 'h3=":443"; ma=86400'}

### 1.3. Obten Error 404

In [138]:
# Publicación con url no válida
error_resp = requests.get(url_nivel_1 + 'posts/url_invalida')
print('Respuesta a consulta errónea:', error_resp.status_code)

Respuesta a consulta errónea: 404

### 1.4. POST nueva publicación
Haz una petición `POST` para crear una nueva publicación fictícia. Incluye el título, el cuerpo del mensaje y un user Id.

In [139]:
nova_post = {'title': 'NOU TÍTOL VAN', 'body': 'Aquí va el text de la nova publicació de la sra. Van', 'userId': 10}
post_resp = requests.post(url_nivel_1 + 'posts', json=nova_post)
print('POST - Codi estat:', post_resp.status_code)
print('Resposta JSON:', post_resp.json())

POST - Codi estat: 201
Resposta JSON: {'title': 'NOU TÍTOL VAN', 'body': 'Aquí va el text de la nova publicació de la sra. Van', 'userId': 10, 'id': 101}

### 1.5. PATCH modificar

In [140]:
patch_data = {'title': 'El meu Títol modificat'}
patch_resp = requests.patch(url_nivel_1 + 'posts/1', json=patch_data)
print('PUT - Codi estat:', patch_resp.status_code)
print('Resposta JSON:', patch_resp.json())

PUT - Codi estat: 200
Resposta JSON: {'userId': 1, 'id': 1, 'title': 'El meu Títol modificat', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

### 1.6. DELETE

In [141]:
delete_resp = requests.delete(url_nivel_1 + 'posts/1')
print('DELETE - Codi estat:', delete_resp.status_code)
print('Resposta JSON:', delete_resp.json())

DELETE - Codi estat: 200
Resposta JSON: {}

# Nivel 2: API Pública Real (Public APIs)

### 2.1 Elegimos una API de la lista https://api.publicapis.org/entries?title=Cat  
- **API elegida: Aviationstack API**  

### 2.2 Lee la documentación de la API:
-   **API documentation**: `https://docs.apilayer.com/aviationstack/docs/api-documentation`
-   Revisa la sección de endpoints disponibles. En un markdown, anota mínimo dos endpoints diferentes.
-   Comprueba si ofrece filtros o parámetros opcionales interesantes. En un markdown, anótalos.
-   Verifica que la respuesta sea en JSON (el más adecuado para este ejercicio).

- Endpoints: 
    `/v1/flights` (Real‑time or historical flights)
    `/v1/airports` (Global airports)

- Base URL: `https://api.aviationstack.com/v1`
- Parámetros `/v1/flights`:
    airline_iata : string  
    airline_icao : string  
    airline_name : string  
    arr_iata : string  
    arr_icao : string  
    arr_scheduled_time_arr : string  
    callback :string  
    dep_iata:string  
    dep_icao:string  
    dep_scheduled_time_dep:string  
    flight_date:string  
    flight_iata:string  
    flight_icao:string  
    flight_num:  
    flight_status: Not Set/scheduled/active/landed/cancelled/incident/diverted  
    limit:defaults to: 100  
    max_delay_arr:integer  
    max_delay_dep:integer  
    min_delay_arr:integer    
    min_delay_dep:integer  
    offset  

- Parámetros `/v1/airports`:
    `callback` string (Optional JSONP callback function name; if provided, response is wrapped for JSONP)  
    `limit` defaults to: 100 (Number of results per page) >= 1  
    `offset` defaults to: 0 (Pagination offset. Use with limit for paging through results.) >= 0  
    `search` string (Free-text search / autocomplete)  

- Resposta: sí, formato JSON.

### 2.3 Haz una petición GET sencilla
- Muestra el código de estado de la respuesta.  
- Imprime de forma clara algunos de los campos de la respuesta JSON.

In [ ]:
params = {
  'access_key': 'codigo_personal',
  'dep_iata': 'BCN'
}

api_result = requests.get('https://api.aviationstack.com/v1/flights', params)
api_response = api_result.json()

In [143]:
print(f'Código estado respuesta: {api_result.status_code}')

Código estado respuesta: 200

In [144]:
for flight in api_response['data']:
        airline = flight['airline']['name'] if flight['airline'] else 'Desconeguda'
        flight_iata = flight['flight']['iata'] if flight['flight'] else 'N/A'
        dep_airport = flight['departure']['airport'] if flight['departure'] else 'N/A'
        dep_iata = flight['departure']['iata'] if flight['departure'] else 'N/A'
        arr_airport = flight['arrival']['airport'] if flight['arrival'] else 'N/A'
        arr_iata = flight['arrival']['iata'] if flight['arrival'] else 'N/A'
        print(airline, flight_iata, dep_airport,arr_airport, arr_iata)

Qatar Airways QR3613 El Prat De Llobregat Orly ORY
Miami Air International LL5620 El Prat De Llobregat Orly ORY
Iberia IB5198 El Prat De Llobregat Orly ORY
Miami Air International LL5685 El Prat De Llobregat Lisbon Portela LIS
Iberia IB5232 El Prat De Llobregat Lisbon Portela LIS
Qatar Airways QR3554 El Prat De Llobregat Charles De Gaulle CDG
Miami Air International LL5645 El Prat De Llobregat Charles De Gaulle CDG
Iberia IB5038 El Prat De Llobregat Charles De Gaulle CDG
Iberia IB5889 El Prat De Llobregat Barajas MAD
Miami Air International LL3020 El Prat De Llobregat Barajas MAD
SA AVIANCA AV6153 El Prat De Llobregat Barajas MAD
Qatar Airways QR6895 El Prat De Llobregat Barajas MAD
LATAM Airlines LA1586 El Prat De Llobregat Barajas MAD
Vueling VY5090 El Prat De Llobregat Barajas MAD
Miami Air International LL5556 El Prat De Llobregat Heathrow LHR
Iberia IB5643 El Prat De Llobregat Heathrow LHR
British Airways BA8077 El Prat De Llobregat Heathrow LHR
Ethiopian Airlines ET1551 El Prat De Llobregat Frankfurt International Airport FRA
Qatar Airways QR4698 El Prat De Llobregat Schiphol AMS
Miami Air International LL5671 El Prat De Llobregat Schiphol AMS
Iberia IB5226 El Prat De Llobregat Schiphol AMS
Uzbekistan Airways HY7298 El Prat De Llobregat Istanbul Airport IST
SA AVIANCA AV6614 El Prat De Llobregat Istanbul Airport IST
IndiGo 6E4356 El Prat De Llobregat Istanbul Airport IST
Iberia IB5887 El Prat De Llobregat Barajas MAD
Lufthansa LH4163 El Prat De Llobregat Franz Josef Strauss MUC
Wizz Air W63178 El Prat De Llobregat Baneasa BBU
DHL Air D0 El Prat De Llobregat Brussels Airport BRU
Qatar Airways QR3593 El Prat De Llobregat Gran Canaria LPA
Miami Air International LL5285 El Prat De Llobregat Gran Canaria LPA
Iberia IB5382 El Prat De Llobregat Gran Canaria LPA
Wizz Air W63406 El Prat De Llobregat Cluj Napoca International Airport CLJ
ASL Airlines Ireland AG4912 El Prat De Llobregat Liege Airport LGG
UPS Airlines 5X243 El Prat De Llobregat Cologne/bonn CGN
Qatar Airways QR3612 El Prat De Llobregat Zurich ZRH
Miami Air International LL5488 El Prat De Llobregat Zurich ZRH
Iberia IB5134 El Prat De Llobregat Zurich ZRH
Qatar Airways QR3728 El Prat De Llobregat Franz Josef Strauss MUC
Miami Air International LL5145 El Prat De Llobregat Franz Josef Strauss MUC
Iberia IB5296 El Prat De Llobregat Franz Josef Strauss MUC
empty None El Prat De Llobregat San Pablo SVQ
Lauda Europe LW7351 El Prat De Llobregat Vienna International VIE
Air Austral UU8549 El Prat De Llobregat Charles De Gaulle CDG
Air Mauritius MK9327 El Prat De Llobregat Charles De Gaulle CDG
Kenya Airways KQ3163 El Prat De Llobregat Charles De Gaulle CDG
Gol G35234 El Prat De Llobregat Charles De Gaulle CDG
Aeromexico AM6028 El Prat De Llobregat Charles De Gaulle CDG
Level LL2605 El Prat De Llobregat Arturo Merino Benitez SCL
Iberia IB2605 El Prat De Llobregat Arturo Merino Benitez SCL
Azores Airlines S48715 El Prat De Llobregat Lisbon Portela LIS
EgyptAir MS9545 El Prat De Llobregat Lisbon Portela LIS
Emirates EK4861 El Prat De Llobregat Lisbon Portela LIS
Azul AD7285 El Prat De Llobregat Lisbon Portela LIS
Qatar Airways QR3514 El Prat De Llobregat Leonardo Da Vinci (Fiumicino) FCO
Miami Air International LL5459 El Prat De Llobregat Leonardo Da Vinci (Fiumicino) FCO
Iberia IB5292 El Prat De Llobregat Leonardo Da Vinci (Fiumicino) FCO
Miami Air International LL3018 El Prat De Llobregat Barajas MAD
Vueling VY5082 El Prat De Llobregat Barajas MAD
Qatar Airways QR6562 El Prat De Llobregat Barajas MAD
BoA OB5007 El Prat De Llobregat Barajas MAD
ASL Airlines Ireland AG421 El Prat De Llobregat Milano Malpensa MXP
Singapore Airlines SQ2812 El Prat De Llobregat Brussels Airport BRU
Etihad Airways EY7272 El Prat De Llobregat Brussels Airport BRU
Qatar Airways QR3536 El Prat De Llobregat Norte Los Rodeos TFN
Miami Air International LL5309 El Prat De Llobregat Norte Los Rodeos TFN
Iberia IB5451 El Prat De Llobregat Norte Los Rodeos TFN
DHL Air D0 El Prat De Llobregat Halle LEJ
Wizz Air W66728 El Prat De Llobregat Marco Polo VCE
Qatar Airways QR3509 El Prat De Llobregat Pablo Ruiz Picasso AGP
Miami Air International LL5194 El Prat De Llobregat Pablo Ruiz Picasso AGP
Iberia IB5005 El Prat De Llobregat Pablo Ruiz Picasso AGP
Qatar Airways QR3590 El Prat De Llobregat Orly ORY
Miami Air International LL5628 El Prat De Llobregat Orly ORY
Iberia IB5206 El Prat De Llobregat Orly ORY
Ryanair FR3800 El Prat De Llobregat Birmingham Airport BHX
easyJet U27682 El Prat De Llobregat Lisbon Portela LIS
Ryanair FR8574 El Prat De Llobregat Leonardo Da Vinci (Fiumicino) FCO
Qatar Airways QR142 El Prat De Llobregat Doha International DOH
LATAM Airlines LA1585 El Prat De Llobregat Barajas MAD
SA AVIANCA AV6019 El Prat De Llobregat Barajas MAD
Xiamen Airlines MF9324 El Prat De Llobregat Schiphol AMS
Korean Air KE6406 El Prat De Llobregat Schiphol AMS
Gol G35624 El Prat De Llobregat Schiphol AMS
Garuda Indonesia GA9257 El Prat De Llobregat Schiphol AMS
Aeromexico AM6359 El Prat De Llobregat Schiphol AMS
Thai Airways International TG7633 El Prat De Llobregat Frankfurt International Airport FRA
ANA NH5450 El Prat De Llobregat Frankfurt International Airport FRA
Etihad Airways EY3765 El Prat De Llobregat Frankfurt International Airport FRA
British Airways BA7083 El Prat De Llobregat Barajas MAD
Miami Air International LL3016 El Prat De Llobregat Barajas MAD
Qatar Airways QR6587 El Prat De Llobregat Barajas MAD
Vueling VY9563 El Prat De Llobregat Heathrow LHR
American Airlines AA6821 El Prat De Llobregat Heathrow LHR
Iberia IB3666 El Prat De Llobregat Heathrow LHR
Malaysia Airlines MH9705 El Prat De Llobregat Heathrow LHR
Qatar Airways QR5520 El Prat De Llobregat Kastrup CPH
Miami Air International LL5163 El Prat De Llobregat Kastrup CPH
Iberia IB5308 El Prat De Llobregat Kastrup CPH
Air Europa UX3128 El Prat De Llobregat Leonardo Da Vinci (Fiumicino) FCO
China Eastern Airlines MU4423 El Prat De Llobregat Leonardo Da Vinci (Fiumicino) FCO

In [145]:
df_aviationstack_BCN = pd.json_normalize(api_response['data'])
df_aviationstack_BCN.head()
# df_aviationstack_BCN.sample(15)

,flight_date,flight_status,live,departure.airport,departure.timezone,departure.iata,departure.icao,departure.terminal,departure.gate,departure.delay,...,flight.codeshared.airline_icao,flight.codeshared.flight_number,flight.codeshared.flight_iata,flight.codeshared.flight_icao,aircraft.registration,aircraft.iata,aircraft.icao,aircraft.icao24,flight.codeshared,aircraft
0,2026-03-02,scheduled,None,El Prat De Llobregat,Europe/Madrid,BCN,LEBL,1,B55,NaN,...,vlg,8008,vy8008,vlg8008,NaN,NaN,NaN,3424D1,NaN,NaN
1,2026-03-02,scheduled,None,El Prat De Llobregat,Europe/Madrid,BCN,LEBL,1,B55,NaN,...,vlg,8008,vy8008,vlg8008,NaN,NaN,NaN,3424D1,NaN,NaN
2,2026-03-02,scheduled,None,El Prat De Llobregat,Europe/Madrid,BCN,LEBL,1,B55,NaN,...,vlg,8008,vy8008,vlg8008,NaN,NaN,NaN,3424D1,NaN,NaN
3,2026-03-02,active,None,El Prat De Llobregat,Europe/Madrid,BCN,LEBL,1,B34,NaN,...,vlg,8464,vy8464,vlg8464,NaN,NaN,NaN,34768D,NaN,NaN
4,2026-03-02,active,None,El Prat De Llobregat,Europe/Madrid,BCN,LEBL,1,B34,NaN,...,vlg,8464,vy8464,vlg8464,NaN,NaN,NaN,34768D,NaN,NaN

En este caso `pd.json_normalize()` es mejor que `pd.DataFrame()` porque aplana directamente en columnas separadas los campos anidados com departure.iata, airline.name, etc.).

# Nivell 3: Open Data BCN (CKAN API)

Más info: https://opendata-ajuntament.barcelona.cat/ca/desenvolupadors#APIS

URL base: `https://opendata-ajuntament.barcelona.cat/data/api/`

EJERCICIO:
1. Busca un dataset de tu interés con package_search y package_show. 
2. De los resultados, selecciona uno que tenga recursos disponibles en CSV o JSON.
3. Con el resource_id del recurso seleccionado, realiza una consulta mediante datastore_search para recuperar al menos 100 registros.
4. Convierte los resultados en un DataFrame.
5. Guarda el DataFrame en un fichero .csv.

In [168]:
# Encuentro listado de  para ver palabras clave para package_Search:
url = "https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_list"
resposta_llista_datasets = requests.get(url)
data = resposta_llista_datasets.json()

datasets = data['result']
print(f"Total datasets: {len(datasets)}")
for unitat in datasets:
    print(unitat)

Total datasets: 553
20170706-districtes-barris
accessibilitat-via-publica
accidents_causa_conductor_gu_bcn
accidents-causes-gu-bcn
accidents-gu-bcn
accidents-persones-gu-bcn
accidents-tipus-gu-bcn
accidents-vehicles-gu-bcn
accions-formatives-adrecades-al-personal
acollida-animals
administracio-autonomica
administracio-estatal
administracio-municipal
afectacions-turistiques
afectacions-turistiques-a-espais-verds
aforaments-descriptiu
aforaments-detall
aforament-tipus-equipament
agenda-activitats-esportives
agenda-cultural
agenda-diaria
agenda-publica-alcaldesa
agendes-publiques-comissionats
agendes-publiques-regidors
alcaldes-alcaldesses-bcn
allotjaments-altres
allotjaments-hotels
allotjaments-pensions
ampliacio-voreres-bici-bcn
aparcaments-bcn
aparcaments-servei-bicis
aparcaments-sota-superficie
arbrat-parcs
arbrat-viari
arbrat-zona
arbres-interes-local
arees-esbarjo-gossos-bcn
atles-biodiversitat-arbrat-especies
atles-biodiversitat-arbrat-geometries
atles-biodiversitat-arbrat-rel-geometria-especie
atles-biodiversitat-flora-especies
atles-biodiversitat-flora-geometries
atles-biodiversitat-flora-rel-geometria-especie
atles-renda-bruta-per-llar
atles-renda-bruta-per-persona
atles-renda-index-gini
atles-renda-mediana
atles-renda-mitjana
atles-renda-p80-p20-distribucio
autenticacions-punts-recarrega-electric
aut-terrasses-excep-decret-21-5
bancs-del-temps-bcn
barcelona-activa-projectes
benzineres
biblioteca_arus_bcnroc
bicicletes
bicing
calendari-festes-laborals
campanyes-publicitat-institucional
capacitat-mapa-estrategic-soroll
carrecs-electes-comissionats-i-gerents
carrerer
carrers-30-bcn
carrers-pacificats-bici-bcn
carrers-plataforma-unica-bcn
carrers-vianants-bcn
carril-bici
carrils-bici-en-construccio
carrils-bici-municipis
carta-arqueologica-barcelona
cataleg-bases-ajuts-subvencions-bcnroc
cataleg-bases-us-espai-public-bcnroc
cataleg-bcnroc
cataleg-cartes-de-serveis-i-politiques-de-qualitat-bcnroc
cataleg-cartobcn
cataleg-circulars-bcnroc
cataleg-comptes-bcnroc
cataleg-costos-bcnroc
cataleg-declaracions-institucionals-bcnroc
cataleg-decrets-alcaldia-bcnroc
cataleg-dictamens-bcnroc
cataleg-directrius-bcnroc
cataleg-documents-alcaldes-bcnroc
cataleg-documents-tecnics-bcnroc
cataleg-dossiers-notes-premsa-bcnroc
cataleg-enquestes-bcnroc
cataleg-estatuts-bcnroc
cataleg-fotografies-art-public-bcnroc
cataleg-fotografies-barcelona-general-bcnroc
cataleg-fotografies-cementiris-bcnroc
cataleg-fotografies-edificis-bcnroc
cataleg-fotografies-elements-urbans-bcnroc
cataleg-fotografies-projectes-urbans-bcnroc
cataleg_fotografies_temes_bcnroc
cataleg-havana-bcnroc
cataleg-informes-avaluacio-bcnroc
cataleg-informes-diversos-bcnroc
cataleg-informes-organs-govern-bcnroc
cataleg-instruccions-bcnroc
cataleg-laudes-bcnroc
cataleg-memories-bcnroc
cataleg-mesures-govern-bcnroc
cataleg-opendata
cataleg-ordenances-fiscals-preus-bcnroc
cataleg-ordenances-municipals-bcnroc
cataleg-plans-especials-bcnroc
cataleg-plans-estrategics-bcnroc
cataleg-premis-bcnroc
cataleg-pressupostos-bcnroc
cataleg-protocols-bcnroc
cataleg-publicacions-bcnroc
cataleg-reglaments-bcnroc
cataleg-rei-bcnroc
cataleg-revistes-bcnroc
cementiris
cens-activitats-economiques-class-bcn
cens-animals-companyia
cens-locals-planta-baixa-act-economica
centres-civics-activitatsdifusio
centres-civics-entitats
centres-civics-formacio
centres-civics-metres-quadrats
cinemes-dades-globals
cobertura-vegetal-ndvi
cohesio-social
colors-aparcaments-superficie
comissaries-policia
compatibilitats
compliment-objectius-estabilitat
comportament-energetic-edificis
confort-termic
consolats-bcn
consum-aigua
consum-electricitat-bcn
contaminacio-atmosferica
contaminants-estacions-mesura-qualitat-aire
contractes-menors
contractes-menors-a-generica
corredors-bici-bcn
culturailleure-bibliotequesimuseus
culturailleure-cinemesteatresauditoris
culturailleure-espaisinfantils
culturailleure-espaismusicacopes
culturailleure-espaisparticipaciociutadana
culturailleure-parcsjardins
dades-arts-esceniques
dades-arxius
dades-ateneus
dades-festes-ciutat
dades-festival-grec
dades-festivals
dades-globals-cultura
dades-grans-auditoris
dades-merce
dades-museus-exposicions
dades-projectes-fabriques-creacio
dades-sales-musica-viu-agrup-dimensions
dades-sindicals
dades-xarxa-biblioteques-catalunya
deficit-proximitat-espai-verd
densitat-activitats
densitat-huts
denuncies_sancions_transit_bcn_codis
denuncies_sancions_transit_bcn_conceptes_annex
denuncies_sancions_transit_bcn_detall
denuncies_sancions_transit_bcn_tip_vehicle
dutxes-platges
ebsib-bcn-enquesta-benestar-subjectiu-infancia
edificis-amics-de-la-bici-barcelona
educacio-ensenyament-infantil
educacio-ensenyament-no-reglat
educacio-ensenyament-reglat
enquesta-escletxa-digital
entitas-pacte-mobilitat
entitats
entitats-municipals
equipament-administracio
equipament-animals-i-plantes
equipament-associacions
equipament-cementiris-i-serveis-relacionats
equipament-centres-d-informacio
equipament-companyies-de-serveis
equipament-cultura-i-lleure
equipament-educacio
equipament-esports
equipament-medi-ambient-i-serveis-relacionats
equipament-mercats-i-centres-comercials
equipament-mitjans-de-comunicacio-i-serveis-relacionats
equipament-restaurants
equipament-sanitat
equipaments-culturals-icub
equipament-serveis-religiosos
equipament-serveis-socials
equipaments-i-parcs-refugi
equipaments-relacionats-amb-transports
equipament-transports-i-serveis-relacionats
escales-mecaniques
esm-bcn-evo
espais-creacio-activitats-difusio
espais-creacio-formacio-professionals
espais-creacio-metres-quadrats
espais-prioritaris-neteja-barcelona
espais-verds-publics
esports-equip
esports-individuals
esports-instal-lacions-esportives
estacionaments-dum
estacions-bus
estacions-maritimes
estat-estacions-bicing
estat-ports-recarrega-electric
est-cadastre-carrecs-quota-cadastral
est-cadastre-carrecs-tipus-propietari
est-cadastre-carrecs-us
est-cadastre-carrecs-valors-cadastrals
est-cadastre-edificacions-any-const
est-cadastre-edificacions-edat-mitjana
est-cadastre-edificacions-nombre-locals
est-cadastre-edificacions-superficie
est-cadastre-finques-regim-propietat
est-cadastre-finques-superficie
est-cadastre-habitatges-any-const
est-cadastre-habitatges-edat-mitjana
est-cadastre-habitatges-propietari
est-cadastre-habitatges-superficie
est-cadastre-habitatges-superficie-mitjana
est-cadastre-habitatges-valor-cadastral
est-cadastre-locals-prop
est-cadastre-locals-sup
est-cadastre-locals-us-desti
est-cadastre-locals-valors-total-unitaris
est-demo-taxa-migracio-interna
est-densitat
est-eleccions-autonomiques-seccio-censal
est-eleccions-europees-seccio-censal
est-eleccions-generals-seccio-censal
est-eleccions-locals-seccio-censal
est-social-discapacitats-grau
est-social-discapacitats-grups-edat
est-social-discapacitats-sexe
est-social-discapacitats-tipus
est-superficie
est-vehicles-amb-distintiu
est-vehicles-antiguitat-menys-un-any
est-vehicles-antiguitat-motos
est-vehicles-antiguitat-tipus
est-vehicles-antiguitat-turismes
est-vehicles-cilindrada-motos
est_vehicles_evolucio_total
est_vehicles_index_motor
est-vehicles-nacionalitat-propietari
est-vehicles-nacionalitat-propietari-motos
est-vehicles-potencia-fiscal-turismes
est_vehicles_propulsio
est_vehicles_servei
est-vehicles-tipologia-parc-vehicles
est-vehicles-tipus-propietari
est-vehicles-tipus-propietari-motos
evolucio-despeses-corrents-per-politiques
evolucio-despeses-per-capitols
evolucio-despeses-per-capitols-i-articles
evolucio-despeses-per-unitats-organiques
evolucio-deute
evolucio-ingressos-per-capitols
evolucio-ingressos-per-capitols-i-articles
evolucio-resultat-ingressos-i-despeses
exclusio-residencial
facanes-mapa-estrategic-soroll
factor-de-vulnerabilitat
fitxer_entitats
fitxes-ocupacionals
fonts
fonts-ornamentals
formacio-poblacio-insuficient
frase
funiculars
galeries-comercials
grans-centres-comercials
grans-establiments
gruamunicipalbcn-retirada-codis
gruamunicipalbcn-retirada-diposits
gruamunicipalbcn-retiradavehicles
h2mave-anualt1b
h2mave-anualt2b
h2mave-anualt3b
h2mave-semestralt1b
h2mave-semestralt2b
h2mave-semestralt3b
h2mave-totalt1b
h2mave-totalt2b
h2mave-totalt3b
h2mave-totalt4b
h2mave-totalt5b
habitatges-2na-ma
habitatges-us-turistic
habit-fam-dest-habit-segons-any-const
habit-fam-sit-edif-dest-habit-segons-tip
habit-ppal-segons-any-const
habit-ppal-segons-estat-conserv-edif
habit-ppal-segons-instal1-calef
habit-ppal-segons-instal2-aigua
habit-ppal-segons-instal3-telf-i-int
habit-ppal-segons-nombre-pers-viuen
habit-ppal-segons-nom-habit
habit-ppal-segons-regim-tin
habit-ppal-segons-sup-util
horaris-aparcaments-superficie
horts-urbans
immobles-quotes-padro-ibi
immo-edif-hab-segons-any-construccio
immo-edif-hab-segons-estat-conservacio
immo-edif-hab-segons-instalacions
immo-edif-hab-segons-num-plantes-sobre-rasant
immo-edif-hab-segons-num-plantes-sota-rasant
impacte-de-la-calor
incidents-gestionats-gub
indicadors-transparencia-pressupostaria
informacio-estacions-bicing
informacio-punts-recarrega-electric
informacio-rutes-autobus-estacio-del-nord
infraestructures-inventari-bancs
infraestructures-inventari-cameres
infraestructures-inventari-inscripcions
infraestructures-inventari-pas-vianants
infraestructures-inventari-pilones
infraestructures-inventari-reductors-velocitat
infraestructures-inventari-reserves
infraestructures-inventari-semafors
infraestructures-inventari-senyalitzacio
infraestructures-inventari-senyals
infraestructures-inventari-separa-carrils-bici
infraestructures-inventari-suports
infraestructures-tipologia-inscripcions
infraestructures-tipologia-pas-vianants
infraestructures-tipologia-semafors
infraestructures-tipologia-senyals
infraestructures-tipologia-suports-cameres
intensitat-activitat-turistica
iris
isofones-mapa-estrategic-soroll
itineraris
laterals-tallats-transit-bici-bcn
lavabos-publics
limits-municipals-districtes
llista-exposicions-temporals
llocs-culte
lloguer-de-vehicles
locve-evolucio
manteniment-lloguer
mapa-acustic-wms
mapa-ambits-urbanistics-wms
mapa-base-de-vialitat
mapa-base-guia
mapa-base-topografic
mapa-construccions-poblament-wms
mapa-de-la-malla-de-fulls-utm
mapa-de-retolacio-de-carrers
mapa-energia-teleco-wms
mapa-graf-viari-carrers-wms
mapa-hidrografia-obres-wms
mapa-orografia-relleu-wms
mapa-parcelari
mapa-peuat
mapa-planol-ciutat-bcn-wms
mapa-serveis-publics-wms
mapa-urbanistic
mapa-usos-sol-wms
mapa-vegetacio-wms
mapa-xarxa-topografica-municipal-wms
mapes-immissio-qualitat-aire
mediambient-contenidorssal
mediambient-puntsrecollidaarbresnadal
mediambient-puntsrobaamiga
mediambient-puntsverdsbarri
mediambient-puntsverdsmobils
mediambient-puntverdcolaborador
mercats-fires-carrer
mercats-municipals
mesures-estacions-meteorologiques
metadades-estacions-meteorologiques
metadades-variables-est-meteo
mobilitat-quotidiana
modificacions-credit-pressupost
modificacions-de-contractes
n-edif-hab-n-immo-edif
n-edif-hab-segons-any-construc
n-edif-hab-segons-estat-cons-edifici
n-edif-hab-segons-instal
n-edif-hab-segons-n-immo
n-edif-hab-segons-nombre-immo
n-edif-hab-segons-nombre-plantes
n-edif-hab-segons-nombre-plantes-sobre-rasant
n-edif-hab-segons-nombre-plantes-sota-rasant
n-edif-hab-segons-n-places-gar
n-edif-hab-segons-n-plantes-sobre-rasant
n-edif-hab-segons-n-plantes-sota-rasant
n-edif-hab-tipus-edif
nomenclator-bcn
np-asia-dipositsvehicles-bcn
np-circuits-caminar-correr
np-esculleres
np-espais-gimnastica
np-jardins-botanics
np-jardins-interiors-illa
np-molls
np-nasia-diposits-aigues-pluvials
np-nasia-fossars
np-nasia-miradors
np-piscines
np-plantes-depuradores
np-platges
np-quioscs-tramits
np-umbracles
obres
oferta-publica
ordenances-municipals
pad_alt_mdbas
pad_bai_mdbas
pad_cdo_b_barri-des
pad_def_mdbas
pad-dimensions
pad_dom_mdbas_dones
pad_dom_mdbas_edat-0018
pad_dom_mdbas_edat-1864
pad_dom_mdbas_edat-6599
pad_dom_mdbas_homes
pad_dom_mdbas_nacionalitat
pad_dom_mdbas_nacionalitat_edat
pad_dom_mdbas_n-persones
pad_dom_mdbas_tipus-domicili
pad_dom_mdbas_tipus-domicili_edat
pad_emi_mdbas
pad_emi_mdbas_nacionalitat-g
pad_imm_mdbas
pad_imm_mdbas_nacionalitat-g
pad_m_cognom
pad_mdbas
pad_mdbas_edat-1
pad_mdbas_edat-q
pad_mdba_sexe_edat-1
pad_mdba_sexe_edat-q
pad_mdbas_lloc-naix_sexe
pad_mdbas_nacionalitat-continent_sexe
pad_mdbas_nacionalitat-g_sexe
pad_mdbas_niv-educa-esta_sexe
pad_mdbas_sexe
pad_mdb_lloc-naix-continent_edat-q_sexe
pad_mdb_lloc-naix_edat-q_sexe
pad_mdb_lloc-naix-regio_sexe
pad_mdb_nacionalitat-contintent_edat-q_sexe
pad_mdb_nacionalitat-g_edat-q_sexe
pad_mdb_nacionalitat-regio_sexe
pad_mdb_niv-educa-esta_edat-lloc-naix
pad_mdb_niv-educa-esta_edat-q_sexe
pad_m_nom_decada_sexe
pad_m_nom_sexe
pad_nai_mdbas
pad_sol_mdb_sexe_edat-q
parades-de-taxi
patis-escolars
patrimoni-arquitectonic-protegit
pbd-cataleg-continguts
p-cons-inicials-segons-lgep-loepsf
perfil-contractant
piezometres_detall
piezometres_equipaments
plantilla-municipal
plaques-fotovoltaiques
plaques-fotovoltaiques-tipologia
poblacio-exposada-mapa-estrategic-soroll
poblacio_projectada
poblacio-vulnerable
precipitacio-hist-bcn
prediccio-meteorologica-del-barcelones
presencia-absencia-vegetacio
pressupost-despeses
pressupost-ingressos
prorrogues-de-contractes
provisio-promocio
proximitat-espais-verds
punts-ancoratge-bicicletes
punts-critics-neteja-barcelona
punts-informacio-turistica
punts-recarrega-vehicles-electrics
punts-verds
punts-wifi
qualificacions-elements-urbanistics
qualitat-aire-detall-bcn
qualitat-aire-estacions-bcn
rasters-mapa-estrategic-soroll
rebuts-quota-padro-guals
rebuts-quota-padro-iae
rebuts-quota-padro-residus-bcn
rebuts-quota-padro-vehicle-bcn
rebuts-quota-padro-vetlladors-terrasses
recintes-gran-aforament
registre-de-convenis
registre-estudis-i-informes
relacio-contractistes
renda-disponible-llars-bcn
renda-tributaria-per-persona-atlas-distribucio
renda-tributaria-unitat-consum-atlas-distribucio
resums-trimestrals-contractacio
risc-contaminacio-acustica
ronda-verda
sanitat-farmacies
sanitat-hospitals-atencio-primaria
sanitat-serveis-sanitaris
servei-cataleg-metadades-csw
serveissocials-centresdiagentgran
serveissocials-centresserveissocials
serveissocials-equipsatencioinfanciaadolescencia
serveissocials-habitatgestutelats
serveissocials-menjadorssocials
serveissocials-oficinesbenestarsocial
serveissocials-puntsassessoramentenergetic
serveissocials-puntsinformacioiatenciodones
serveissocials-residenciesgentgran
subvencions-a-ens-publics-no-integrats-cercador-post-2019
subvencions-atorgades-ajuntament-i-instituts
subvencions_entitats_nfge
subvencions-i-transferencies-a-ens-publics
subvencions-transferencies-cultura
tanatoris
tarifes-aparcament-superficie
taula-direle
taula-direle-sec-cens
taula-map-illa
taula-segimon
teleferics
temperatures-hist-bcn
terrasses-comercos-vigents
tramer-mapa-estrategic-soroll
trams
trams-aparcament-superficie
transferencies-encomanes-gestio
transitaeri_flightradar_ppal_aeroport
transitaeri_flightradar_ppal_comp_zona
transitaeri_flightradar_ppal_pais
transit-relacio-trams
transit-relacio-trams-per-itinerari
transports
transports-metropolitants-companyies-autocars-de-barcelona
us-del-servei-bicing
viatges-govern-bcn
vies-ciclables
xarxa-refugis-climatics
xarxasoroll-equipsmonitor-dades
xarxasoroll-equipsmonitor-instal
zbe-ambit
zones30-carrers
zones-carrega-descarrega
zones-estacionament-zona-bus

#### Buscar un dataset de tu interés mediante package_search y package_show.

In [169]:
paraules_clau = ["transit aeri"]
base_url = "https://opendata-ajuntament.barcelona.cat/data/api/3/action"


resultats_totals = []

for paraula in paraules_clau:
    url = f"{base_url}/package_search"
    params = {"q": paraula, "rows": 10}
    response = requests.get(url, params=params)
    data = response.json()
    
    resultats = data["result"]["results"]
    print(f"\n '{paraula}': {len(resultats)} resultats:")
    for resultat in resultats:
        print(f"  - {resultat['name']} | {resultat['title']}")
        resultats_totals.append({
            "paraula_clau": paraula,
            "name": resultat["name"],
            "title": resultat["title"],
            "num_resources": len(resultat.get("resources", []))
            })

print(f"\n Total resultats trobats: {len(resultats_totals)}")

 'transit aeri': 3 resultats:
  - transitaeri_flightradar_ppal_pais | Number of aircraft operations at the Josep Tarradellas Barcelona-El Prat airport by main destination or origin countries
  - transitaeri_flightradar_ppal_aeroport | Number of aircraft operations at the Josep Tarradellas Barcelona-El Prat airport by main destination or origin airports
  - transitaeri_flightradar_ppal_comp_zona | Number of aircraft operations at the Josep Tarradellas Barcelona-El Prat airport by main airlines and geographic area of ​​destination or origin

 Total resultats trobats: 3

#### De los resultados, selecciona uno que tenga recursos disponibles en CSV o JSON.

In [170]:
for r in info_dataset.json()['result']['resources']:
    if r['format'].upper() in ['CSV', 'JSON']:
        resources = r
        break

print('Format del recurs:', resources['format'])
resource_id = resources['id']

Format del recurs: CSV

#### Con el resource_id, realiza una consulta mediante datastore_search para recuperar al menos 100 registros.

In [171]:
ckan_url = 'https://opendata-ajuntament.barcelona.cat/data/api/3/action/'

# package_search
search_resp = requests.get(ckan_url + 'package_search?q=transitaeri')
dataset_trobat = search_resp.json()['result']['results'][0]
print('Dataset elegido:', dataset_trobat['name'])

# package_show
pkg_name = dataset_trobat['name']
info_dataset = requests.get(ckan_url + f'package_show?id={pkg_name}')
resources = info_dataset.json()['result']['resources'][0]
resource_id = resources['id']
print('Resource ID:', resource_id)

# datastore_search (100 registros)
resposta3 = requests.get(ckan_url + f'datastore_search', params={'resource_id': resource_id, 'limit': 100})
records = resposta3.json()['result']['records']
print('Registros obtenidos:', len(records))

Dataset elegido: transitaeri_flightradar_ppal_pais
Resource ID: daaf92f4-8879-40f0-bc35-d550f1f9582a
Registros obtenidos: 100

#### Convierte los resultados en un DataFrame.

In [172]:
df_bcn = pd.DataFrame(records)
print(df_bcn.columns)
df_bcn.head(10)

Index(['Data_Referencia', 'Nom_Pais', 'Nombre_Vols', '_id', 'Codi_Pais'], dtype='object')

       Data_Referencia       Nom_Pais Nombre_Vols  _id Codi_Pais
0  2025-01-01T00:00:00        Espanya         230    1         1
1  2025-01-01T00:00:00         Itàlia         100    2         2
2  2025-01-01T00:00:00     Regne Unit          71    3         3
3  2025-01-01T00:00:00         França          83    4         4
4  2025-01-01T00:00:00       Alemanya          48    5         5
5  2025-01-01T00:00:00       Portugal          38    6         6
6  2025-01-01T00:00:00  Països Baixos          28    7         7
7  2025-01-01T00:00:00         Suïssa          20    8         8
8  2025-01-01T00:00:00        Bèlgica          20    9         9
9  2025-01-01T00:00:00     Marroc, el          28   10        10

#### Guarda el DataFrame en un fichero .csv.

In [173]:
df_bcn.to_csv('opendata_bcn.csv', index=False)
print('Desat a opendata_bcn.csv')

Desat a opendata_bcn.csv